# Generated by Django 5.1 on 2024-08-20 19:44

import app_user.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_previous_history', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='report/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_user.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nid', models.IntegerField(validators=[app_user.validators.validate_nid])),
                ('phone_number', models.CharField(max_length=15, validators=[app_user.validators.validate_phone_number])),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')])),
                ('user_photo', models.ImageField(blank=True, upload_to='images/user/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='user_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='app_user.userdetails'),
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.PositiveIntegerField()),
                ('specialty', models.CharField(max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='app_user.userdetails')),
            ],
        ),
    ]
