# Generated by Django 5.1 on 2024-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
