# Generated by Django 5.1 on 2024-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_patientmodel_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='license_id',
            field=models.CharField(max_length=20),
        ),
    ]
